---
- name: Configure AWS
  hosts: localhost
  roles:
    - aws_start

- name: Deploy neko server
  hosts: neko
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - docker
    - neko
