---
- name: Stop up EC2 instance and get info
  community.aws.ec2_instance:
    state: stopped
    region: "{{ ec2_region }}"
    filters:
      tag-key: neko
  register: neko_instance

- name: Remove elastic IP for the EC2 instance
  community.aws.ec2_eip:
    device_id: "{{ neko_instance.instances[0].instance_id }}"
    release_on_disassociation: yes
    region: "{{ ec2_region }}"
    state: absent
    tag_name: neko
  register: neko_eip

- name: Clean up EC2 instance
  community.aws.ec2_instance:
    state: "{{ ec2_instance_state }}"
    region: "{{ ec2_region }}"
    filters:
      tag-key: neko

- name: Get Route53 info
  community.aws.route53_zone:
    zone: "{{ main_domain_name }}"
  register: hongzai_domain

- name: Get DNS record from Route53
  community.aws.route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{ hongzai_domain.zone_id }}"
    start_record_name: "{{ neko_domain_name }}"
  register: neko_record

- name: Save public IP of EC2 instance
  set_fact:
    neko_ip: "{{ neko_record.list[0].ResourceRecords[0].Value }}"
    neko_ttl: "{{ neko_record.list[0].TTL }}"
    neko_type: "{{ neko_record.list[0].Type }}"
  when: neko_record.list | d(False)

- name: Remove DNS record from Route53
  community.aws.route53:
    state: absent
    zone: "{{ main_domain_name }}"
    record: "{{ neko_domain_name }}"
    type: "{{ neko_type }}"
    ttl: "{{ neko_ttl }}"
    value:
      - "{{ neko_ip }}"
  when: neko_record.list | d(False)
