---
- name: Find an Ubuntu 20.04 Server image
  amazon.aws.ec2_ami_info:
    filters:
      name: "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
      architecture: x86_64
      is-public: true
      root-device-type: ebs
  register: neko_image

- name: Upsert security group
  amazon.aws.ec2_group:
    name: "{{ ec2_security_group }}"
    description: security group for neko application
    tags:
      neko: yes
    rules:
      - cidr_ip: 0.0.0.0/0
        proto: tcp
        ports:
          - 22
          - 80
          - 443
      - cidr_ip: 0.0.0.0/0
        proto: udp
        ports:
          - 59000-59100

- name: Get default vpc info
  amazon.aws.ec2_vpc_net_info:
    filters:
      isDefault: yes
  register: neko_net

- name: Get default subnet info
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ neko_net.vpcs[0].vpc_id }}"
  register: neko_subnet

- name: Get Route53 info
  community.aws.route53_zone:
    zone: "{{ main_domain_name }}"
  register: hongzai_domain
