---
- name: Create key pair in AWS
  amazon.aws.ec2_key:
    name: "{{ ec2_key_name }}"
    key_material: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Get default vpc info
  amazon.aws.ec2_vpc_net_info:
    filters:
      isDefault: yes
  register: neko_net

- name: Get default subnet info
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ neko_net.vpcs[0].vpc_id }}"
  register: neko_subnet

- name: Find an Ubuntu 20.04 Server image
  amazon.aws.ec2_ami_info:
    filters:
      name: "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-*"
      architecture: x86_64
      is-public: true
      root-device-type: ebs
  register: neko_image

- name: Upsert security group
  amazon.aws.ec2_group:
    name: "{{ ec2_security_group }}"
    description: security group for neko application
    vpc_id: "{{ neko_net.vpcs[0].vpc_id }}"
    tags:
      neko: yes
    rules:
      - cidr_ip: 0.0.0.0/0
        proto: tcp
        ports:
          - 22
          - 80
          - 443
      - cidr_ip: 0.0.0.0/0
        proto: udp
        ports:
          - 59000-59100

- name: Start an instance with a public IP address
  community.aws.ec2_instance:
    name: neko
    key_name: "{{ ec2_key_name }}"
    vpc_subnet_id: "{{ neko_subnet.subnets[0].subnet_id }}"
    instance_type: "{{ ec2_instance_type }}"
    security_group: "{{ ec2_security_group }}"
    image_id: "{{ neko_image.images[-1].image_id }}"
    network:
      assign_public_ip: true
    tags:
      neko: true
    state: running
  register: neko_instance

- name: Save public IP address
  set_fact:
    neko_ip: "{{ neko_instance.instances[0].public_ip_address }}"

# - name: Create elastic IP for the EC2 instance
#   community.aws.ec2_eip:
#     allow_reassociation: yes
#     device_id: "{{ neko_instance.instances[0].instance_id }}"
#     release_on_disassociation: yes
#     reuse_existing_ip_allowed: yes
#     in_vpc: yes
#     tag_name: neko
#   register: neko_eip

# - name: Save public IP address
#   set_fact:
#     neko_ip: "{{ neko_eip.public_ip }}"

- name: Update the DNS record to point to EC2 instance
  community.aws.route53:
    state: present
    zone: "{{ main_domain_name }}"
    record: "{{ neko_domain_name }}"
    type: A
    ttl: 300
    value:
      - "{{ neko_ip }}"
    overwrite: yes
    wait: yes

- name: Refresh local cache
  raw: systemd-resolve --flush-caches
  become: yes
