---
- name: Start an instance with a public IP address
  community.aws.ec2_instance:
    name: neko
    key_name: "{{ ec2_key_name }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    instance_type: "{{ ec2_instance_type }}"
    security_group: "{{ ec2_security_group }}"
    image_id: "{{ ec2_image_id }}"
    region: "{{ ec2_region }}"
    network:
      assign_public_ip: true
    tags:
      neko: true
    state: running
  register: neko_instance

- name: Save public IP of EC2 instance
  set_fact:
    neko_ip: "{{ neko_instance.instances[0].public_ip_address }}"

- name: Update the DNS record to point to EC2 instance
  community.aws.route53:
    state: present
    zone: "{{ main_domain_name }}"
    record: "{{ neko_domain_name }}"
    type: A
    ttl: 300
    value:
      - "{{ neko_ip }}"
    overwrite: yes
    wait: yes

- name: Refresh local cache
  raw: systemd-resolve --flush-caches
  become: yes
